[package]
name = "rust-book"
version = "0.0.1"
authors = ["Steve Klabnik <steve@steveklabnik.com>"]
description = "The Rust Book"
edition = "2018"

[[bin]]
name = "concat_chapters"
path = "tools/src/bin/concat_chapters.rs"

[[bin]]
name = "convert_quotes"
path = "tools/src/bin/convert_quotes.rs"

[[bin]]
name = "lfp"
path = "tools/src/bin/lfp.rs"

[[bin]]
name = "link2print"
path = "tools/src/bin/link2print.rs"

[[bin]]
name = "release_listings"
path = "tools/src/bin/release_listings.rs"

[[bin]]
name = "remove_hidden_lines"
path = "tools/src/bin/remove_hidden_lines.rs"

[[bin]]
name = "remove_links"
path = "tools/src/bin/remove_links.rs"

[[bin]]
name = "remove_markup"
path = "tools/src/bin/remove_markup.rs"

[dependencies]
walkdir = "0.1.5"
docopt = "0.6.82"
rustc-serialize = "0.3.19"
regex = "0.1.73"
lazy_static = "0.2.1"
flate2 = "1.0"
tar = "0.4.16"
